'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { StButton as StButtonElement, defineCustomElement as defineStButton } from "@poc-stencil/library/dist/components/st-button.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type StButtonEvents = { onClicked: EventName<CustomEvent<any>> };

export const StButton: StencilReactComponent<StButtonElement, StButtonEvents> = /*@__PURE__*/ createComponent<StButtonElement, StButtonEvents>({
    tagName: 'st-button',
    elementClass: StButtonElement,
    react: React,
    events: { onClicked: 'clicked' } as StButtonEvents,
    defineCustomElement: defineStButton
});
